name: airbrake-ruby

on: [push]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [2.5, 2.6, 2.7, 3.0, 3.1, head, jruby]

        # Temporarily disable jruby-head temporarily because it rubocop-ast
        # chokes on it: https://github.com/airbrake/airbrake-ruby/runs/5969451901
        # with: TypeError: nil can't be coerced into Integer
        #
        # ruby: [2.5, 2.6, 2.7, 3.0, 3.1, head, jruby, jruby-head]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Rubocop lint
      run: bundle exec rubocop

    # Disable for now because Ruby 3.2 + YARD don't work well.
    # There's a YARD bug that has been fixed but not released yet:
    #   * https://github.com/lsegal/yard/pull/1419
    #
    # - name: YARD lint
    #   run: |
    #     touch README # Workaround for "incorrect" anchor links in README.md
    #     bundle exec yardoc --fail-on-warning --no-progress --readme=README

    - name: Display Ruby version
      run: ruby -v

    - name: Test
      run: bundle exec rake
